name: SchemaGuard Auto-Fix

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  run-schemaguard:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run SchemaGuard CLI
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          DATA_REPO_NAME: ${{ secrets.DATA_REPO_NAME }}
          DATAHUB_GMS_URL: ${{ secrets.DATAHUB_GMS_URL }}
          DATAHUB_TOKEN: ${{ secrets.DATAHUB_TOKEN }}
        run: python cli.py
